### ISSUE TITLE
A question about MPSC in audio implementation

### ISSUE THREAD

**Issue by ablakey** [min050820/rust-gb#1]
Hello!

Thanks for writing this emulator. It's been a useful resource to study for learning Rust and emulators.

Why do you use the MPSC here: https://github.com/min050820/rust-gb/blob/master/src/gameboy/sound.rs#L582

My vague understanding leads me to guess: because you want your emulator loop, running in the main thread, to be able to push data into the audio buffer, which is then read by a separate thread (spawned and owned by the SDL audio subsystem?)  And that you couldn't do this without a FIFO queue that lets you write -> read data between threads?

Is that accurate? Is there any other rationale for why you approached it this way?

Thanks for your time.

**Comment by min050820** [comment]
Yes. The main reason is exactly what you described. The audio data needs to cross thread boundary.

Plus, I needed to use size-bounded queue because the main thread needs to sync with audio. It automatically applies frame limiter for main thread because it waits for audio thread to pop them out. No extra frame limiter needed :)

I'm marking this as closed, but please feel free to ask more questions!

**Comment by ablakey** [comment]
Thank you.  I appreciate you sharing some of your time. 

This must mean that the buffer size you have selected must be a function of the proper timing and not just a arbitrarily large enough array. 

I might have future questions but I'm trying my best to piece it together myself as a learning exercise. Thanks for the offer.

**Comment by min050820** [comment]
Buffer size *actually* is just some arbitarily large enough one. It simply can't be **TOO** large. 😂

For example, if FIFO queue was 187 objects long, then audio would be delayed by 1 second, since each object has 256 samples per channel [(src)](https://github.com/min050820/rust-gb/blob/2f0baab8cb8e19f64aaf34060e88c9432fce20be/src/gameboy/sound.rs#L14), and `256 * 187 = 47872 (samples)`, which is around 48000.

Current size of 4 objects would delay audio at most `256 * 4 = 1024 (samples)`, which is around 0.02 seconds. I believe this is unnoticible, hence the code.

**Comment by ablakey** [comment]
Okay that makes sense. Thanks. 

Is it reasonably accurate to perceive the audio system as:

- the sound sink (SDL) drains samples at 48khz. 

- the four sources (square, square, wave, noise) generate samples at 48khz (what tick() returns)

- the four sources are actually operating at a far lower frequency (what the clock is being used for, with the 64, 128, 256 values) 

- they just generate large chunks of samples at a time

- I would expect to see the sample stream having runs of the exact same value as a result of that quantization. 

Is the main tick() function being called ~1 million times per second? Or 48,000?

Thanks again. 

P.s. Here's my Emulator WIP without sound yet.  https://github.com/ablakey/gameboy

**Comment by min050820** [comment]
* the sound sink (SDL) drains samples at 48khz.
* → Correct.
* the four sources (square, square, wave, noise) generate samples at 48khz (what tick() returns)
* → No. They generate samples at `MASTER_FREQ` hz.
* the four sources are actually operating at a far lower frequency (what the clock is being used for, with the 64, 128, 256 values)
* → They generate samples at `MASTER_FREQ`hz, which is ~1 million times per second. `FREQ_DIVISOR` is 4 because every instruction takes multiple of 4 cycles.
* they just generate large chunks of samples at a time
* → Actually, they're called once per instruction. Please look at [z80.rs](https://github.com/min050820/rust-gb/blob/2f0baab8cb8e19f64aaf34060e88c9432fce20be/src/gameboy/z80.rs#L860) and [memory_bus.rs](https://github.com/min050820/rust-gb/blob/2f0baab8cb8e19f64aaf34060e88c9432fce20be/src/gameboy/memory_bus.rs#L70).
* I would expect to see the sample stream having runs of the exact same value as a result of that quantization.
* → More or less correct. I'm not sure I understood this one correctly, but that's probably due to me lacking English skill.

In my emulator, any function named `tick()` is called every machine tick. (That is, 4 times for a NOP.) And any function named `tick(cycles: i32)` batch processes `cycles` tick at once. This is to improve performance by reducing cache misses.

Note: my emulator's sound implementation is not that good. It actually fails at several games, including boot ROM and pokemon.

Good luck implementing emulator!

**Comment by ablakey** [comment]
Hello!

I'm curious what you were attempting here: https://github.com/min050820/rust-gb/blob/master/src/gameboy/sound.rs#L94

It looks like you were doing something about dividing the output buffer samples by the pack_ratio, but then a few lines later just set them to 0.0, negating that effect.

Thanks!

**Comment by min050820** [comment]
@ablakey It's downsampling audio. Please look at point 2 and 3 [up there](https://github.com/min050820/rust-gb/issues/1#issuecomment-782813382).

My emulator generates audio at `MASTER_FREQ` Hz (=1048576 Hz), which is very high. Therefore, my code has to downsample that into something playable by sound cards. The code you're looking at exactly does that. `pack_ratio` stores how many samples from the source (1048576 Hz) should be *packed* into one output sample (48000 Hz). This is not emulator-related in any way, and my approach to doing that is quite naive. You could use a library to do that instead.

I peeked at your project, and your code seems to generate samples at 44100Hz. I ditched that idea because I wasn't sure if that would actually work since 4194304 is not divisible by 48000 (or 44100).

I'm not 100% sure in this respect, so please don't take this as an advice.
